### ISSUE TITLE
ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v2/spans": Failed to connect to localhost/127.0.0.1:9411

### ISSUE THREAD

**Issue by MPParsley** [Informatievlaanderen/VSDS-LDESServer4J#619]
**Describe the bug**
An exception is thrown when posting data to the quickstart server.

**To Reproduce**
1. Follow the steps on https://informatievlaanderen.github.io/VSDS-Tech-Docs/docs/quickstart.html
2. curl -X POST http://localhost:8080/sample -H "Content-Type: application/ttl" -d '@sample.ttl' to post the sample.ttl 

This throws an org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v2/spans": Failed to connect to localhost/127.0.0.1:9411

(same exception as #454)

**Expected behavior**
The object is added to the stream.

**Additional context**
```

quick_start_ldes-server   | org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v2/spans": Failed to connect to localhost/127.0.0.1:9411
quick_start_ldes-server   | 	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinRestTemplateSender$RestTemplateHttpPostCall.doExecute(ZipkinRestTemplateSender.java:68) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinRestTemplateSender$RestTemplateHttpPostCall.doEnqueue(ZipkinRestTemplateSender.java:75) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at zipkin2.Call$Base.enqueue(Call.java:406) ~[zipkin-2.23.2.jar!/:na]
quick_start_ldes-server   | 	at io.opentelemetry.exporter.zipkin.ZipkinSpanExporter.export(ZipkinSpanExporter.java:72) ~[opentelemetry-exporter-zipkin-1.19.0.jar!/:1.19.0]
quick_start_ldes-server   | 	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:326) ~[opentelemetry-sdk-trace-1.19.0.jar!/:1.19.0]
quick_start_ldes-server   | 	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:244) ~[opentelemetry-sdk-trace-1.19.0.jar!/:1.19.0]
quick_start_ldes-server   | 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
quick_start_ldes-server   | Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9411
quick_start_ldes-server   | 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at org.springframework.http.client.OkHttp3ClientHttpRequest.executeInternal(OkHttp3ClientHttpRequest.java:68) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
quick_start_ldes-server   | 	... 9 common frames omitted
quick_start_ldes-server   | Caused by: java.net.ConnectException: Connection refused
quick_start_ldes-server   | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
quick_start_ldes-server   | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
quick_start_ldes-server   | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:539) ~[na:na]
quick_start_ldes-server   | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594) ~[na:na]
quick_start_ldes-server   | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
quick_start_ldes-server   | 	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
quick_start_ldes-server   | 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.10.0.jar!/:na]
quick_start_ldes-server   | 	... 28 common frames omitted
```

**Comment by WLefever-Cegeka** [comment]
Hi @MPParsley ,
@samuvack and I looked at the issue.
The error you logged has to do with tracing. If you add this environment variable to the docker compose, tracing is disabled: `MANAGEMENT_TRACING_ENABLED=false`.
@samuvack also updated the Quick Start.
Can you verify that the issue is resolved?

**Comment by MPParsley** [comment]
Hi @WLefever-Cegeka, thank you for the feedback.

Adding MANAGEMENT_TRACING_ENABLED=false to the nifi container did not resolve the issue.

```
  nifi:
    image: ghcr.io/informatievlaanderen/ldes-workbench-nifi:20230214T123440 #20221109T103745
    container_name: nifi-graph2
    restart: unless-stopped
    ports:
      # HTTPS
      - 8443:8443/tcp
    volumes:
      - ./nifi-extensions:/opt/nifi/nifi-current/extensions
    environment:
      - NIFI_UI_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123456789
      - NIFI_WORKFLOW_LISTEN_PORT=9005
      - NIFI_JVM_HEAP_INIT=8g
      - NIFI_JVM_HEAP_MAX=8g
      - MANAGEMENT_TRACING_ENABLED=false
```

**Comment by MPParsley** [comment]
Another workaround:
```
management:
  tracing:
    enabled: false
```
